package mr

import (
	"encoding/gob"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/rpc"
	"os"
	"sync"
)

type TaskStatus int

const (
	TODO TaskStatus = iota
	IN_PROGRESS
	DONE
)

func (s TaskStatus) String() string {
	return [...]string{"TODO", "IN_PROGRESS", "DONE"}[s]
}

type TaskType int

const (
	MAP TaskType = iota
	REDUCE
)

func (s TaskType) String() string {
	return [...]string{"MAP", "REDUCE"}[s]
}

type Task interface {
	GetType() TaskType
	GetStatus() TaskStatus
}

type MapTask struct {
	ID             int
	Status         TaskStatus
	InputFile      string
	ReduceNum      int
	ImmediateFiles map[int]string // reduce id -> file name
}

func (m MapTask) GetType() TaskType {
	return MAP
}

func (m MapTask) GetStatus() TaskStatus {
	return m.Status
}

type ReduceTask struct {
	ID             int
	Status         TaskStatus     // The status of the reduce task
	ImmediateFiles map[int]string // map id -> file name of the immediate files that are generated by the map tasks
}

func (r ReduceTask) GetType() TaskType {
	return REDUCE
}

func (r ReduceTask) GetStatus() TaskStatus {
	return r.Status
}

type Coordinator struct {
	MapTasks    []MapTask
	ReduceTasks []ReduceTask
	// The key is the worker id, the value is the task assigned to the worker
	// if the task is nil, it means the worker is idle
	Workers map[string]Task

	mutex sync.Mutex // protect the coordinator data structure
}

func (c *Coordinator) GetTask(
	request *GetTaskRequest, response *GetTaskResponse) error {
	log.Printf("📦 Received a GetTask request: %v\n", request)
	c.mutex.Lock()
	defer func() {
		c.mutex.Unlock()
		c.debugInfo()
	}()
	mapTasksAllDone := true
	for mapID, m := range c.MapTasks {
		if m.Status != DONE {
			mapTasksAllDone = false
		}
		if m.Status == TODO {
			c.MapTasks[mapID].Status = IN_PROGRESS
			c.Workers[request.WorkerID] = c.MapTasks[mapID]
			log.Printf("📦 Send a map task: %v\n", c.MapTasks[mapID])
			response.Task = c.MapTasks[mapID]
			return nil
		}
	}
	if !mapTasksAllDone {
		return nil
	}
	for reduceID, r := range c.ReduceTasks {
		if r.Status == TODO {
			c.ReduceTasks[reduceID].Status = IN_PROGRESS
			c.Workers[request.WorkerID] = c.ReduceTasks[reduceID]
			log.Printf("📦 Send a reduce task: %v\n", c.ReduceTasks[reduceID])
			response.Task = c.ReduceTasks[reduceID]
			return nil
		}
	}
	return nil
}

func (c *Coordinator) MarkTaskAsDone(request *MarkTaskAsDoneRequest, response *MarkTaskAsDoneResponse) error {
	c.mutex.Lock()
	defer func() {
		c.mutex.Unlock()
		c.debugInfo()
	}()
	if request.Task.GetType() == MAP {
		mapTask := request.Task.(MapTask)
		if mapTask.ID < 0 || mapTask.ID >= len(c.MapTasks) {
			return fmt.Errorf("invalid map task id: %d", mapTask.ID)
		}
		if c.MapTasks[mapTask.ID].Status != DONE {
			c.MapTasks[mapTask.ID].Status = DONE
			log.Printf("🔥 Mark map task as done: %+v\n", c.MapTasks[mapTask.ID])
			for reduceID, immediateFile := range mapTask.ImmediateFiles {
				c.ReduceTasks[reduceID].ImmediateFiles[mapTask.ID] = immediateFile
			}
		} else {
			// ignore the duplicate map result
			log.Printf("💦 Map task is already done: %+v\n", c.MapTasks[mapTask.ID])
		}
	} else {
		reduceTask := request.Task.(ReduceTask)
		if reduceTask.ID < 0 || reduceTask.ID >= len(c.ReduceTasks) {
			return fmt.Errorf("invalid reduce task id: %d", reduceTask.ID)
		}
		if c.ReduceTasks[reduceTask.ID].Status != DONE {
			c.ReduceTasks[reduceTask.ID].Status = DONE
			log.Printf("🔥 Mark reduce task as done: %+v\n", c.ReduceTasks[reduceTask.ID])
			src := fmt.Sprintf("mr-tmp-out-%d-%s", reduceTask.ID, request.WorkerID)
			dst := fmt.Sprintf("mr-out-%d", reduceTask.ID)
			copyFile(src, dst)
		} else {
			// ignore the duplicate reduce result
			log.Printf("💦 Reduce task is already done: %+v\n", c.ReduceTasks[reduceTask.ID])
		}
	}
	c.Workers[request.WorkerID] = nil
	return nil
}

// start a thread that listens for RPCs from worker.go
func (c *Coordinator) server() {
	gob.Register(MapTask{})
	gob.Register(ReduceTask{})
	rpc.Register(c)
	rpc.HandleHTTP()
	//l, e := net.Listen("tcp", ":1234")
	sockname := coordinatorSock()
	log.Printf("sockname: %s\n", sockname)
	os.Remove(sockname)
	l, e := net.Listen("unix", sockname)
	if e != nil {
		log.Fatal("listen error:", e)
	}
	go http.Serve(l, nil)
}

// main/mrcoordinator.go calls Done() periodically to find out
// if the entire job has finished.
func (c *Coordinator) Done() bool {
	for _, r := range c.ReduceTasks {
		if r.Status != DONE {
			return false
		}
	}
	return true
}

func (c *Coordinator) debugInfo() {
	log.Println("🤖=====================================")
	c.printMapTasks()
	c.printReduceTasks()
	c.printWorkerAssignments()
}

func (c *Coordinator) printMapTasks() {
	log.Println("-------------[map task]--------------")
	for _, task := range c.MapTasks {
		log.Printf("%+v\n", task)
	}
}

func (c *Coordinator) printReduceTasks() {
	log.Println("-------------[reduce task]--------------")
	for _, task := range c.ReduceTasks {
		log.Printf("%+v\n", task)
	}
}

func (c *Coordinator) printWorkerAssignments() {
	log.Println("-------------[worker]--------------")
	for i, task := range c.Workers {
		log.Printf("worker_id=%s: Task=%+v\n", i, task)
	}
}

// create a Coordinator.
// main/mrcoordinator.go calls this function.
// nReduce is the number of reduce tasks to use.
func MakeCoordinator(files []string, nReduce int) *Coordinator {
	// Your code here.
	mapTasks := initMapTasks(files, nReduce)
	reduceTasks := initReduceTasks(nReduce)
	workers := make(map[string]Task)
	c := Coordinator{MapTasks: mapTasks, ReduceTasks: reduceTasks, Workers: workers}
	c.server()
	return &c
}

func initMapTasks(files []string, nReduce int) []MapTask {
	m := make([]MapTask, len(files))
	for i, fileName := range files {
		m[i] = MapTask{
			ID:             i,
			InputFile:      fileName,
			Status:         TODO,
			ReduceNum:      nReduce,
			ImmediateFiles: make(map[int]string, nReduce),
		}
	}
	return m
}

func initReduceTasks(nReduce int) []ReduceTask {
	r := make([]ReduceTask, nReduce)
	for i := 0; i < nReduce; i++ {
		r[i] = ReduceTask{ID: i, Status: TODO, ImmediateFiles: make(map[int]string)}
	}
	return r
}

func copyFile(src, dst string) error {
	// Open the source file for reading.
	srcFile, err := os.Open(src)
	if err != nil {
		return err
	}
	defer srcFile.Close()

	// Create the destination file for writing.
	dstFile, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer dstFile.Close()

	// Copy the contents of the source file to the destination file.
	_, err = io.Copy(dstFile, srcFile)
	if err != nil {
		return err
	}

	// Flush any buffered data to the destination file.
	err = dstFile.Sync()
	if err != nil {
		return err
	}

	return nil
}
